version: '3'
services:
  app:
    container_name: blood-bank-server
    restart: always
    build: .
    ports:
      - '3050:8000'
  chat:
    container_name: chat-server
    restart: always
    build: /home/bigsnap/Desktop/chat-server
    ports:
      - '3051:8001'
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - "db-data:/data/db"
    ports:
      - '27017:27017'
  redis:
    container_name: redis
    image: redis:alpine
    ports:
      - '6379:6379'

volumes:
  db-data: